title: Jeffrey Wigington Portfolio Site
description: > # this means to ignore newlines until "baseurl:"
  This is Jeffrey Wigington's Porfolio site. Here you'll find posts about my projects.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jwig22.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jeff Wigington # add your name
author-img: Jeffrey-Wigington.jpg # add your photo
about-author: I'm Jeff, a Mechnical Engineer moving into Data Science! I went into Engineering because of my aptitude in mathemathics and analyzing data, but didn't know about Data Science yet. My background in Engineering and Robotics&mdash;including motion planning algorithms and machine learning in computer vision&mdash;gives me great overlapping skills for Data Science. Check out my side-projects! # add description
social-github: jwig22 # add your Github handle
social-linkedin: jeffreywigington/ # add your Linkedin handle
social-email: jwigington22@gmail.com # add your Email address

# Disqus
#discus-identifier: # add your discus identifier

# Tracker
# analytics: G-PVJ29CD7PQ # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-remote-theme 

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

